defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

    [entryPoints.https.tls]

  [entryPoints.ping]
    address = ":8082"

  %{ if metrics }
  [entryPoints.metrics]
    address = ":9100"
  %{ endif }

[ping]
  entryPoint = "ping"

[kubernetes]
  ingressClass = "${ class }"

%{ if metrics }
[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
%{ endif }
