defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.ping]
    address = ":8082"

[ping]
  entryPoint = "ping"

[kubernetes]
  ingressClass = "traefik"
